-- V2: Избранное, отзывы, сброс пароля

-- Избранные площадки
CREATE TABLE IF NOT EXISTS favorites (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT    NOT NULL,
    field_id   BIGINT    NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_favorite_user_field UNIQUE (user_id, field_id),
    CONSTRAINT fk_favorites_user  FOREIGN KEY (user_id)  REFERENCES users(id)  ON DELETE CASCADE,
    CONSTRAINT fk_favorites_field FOREIGN KEY (field_id) REFERENCES fields(id) ON DELETE CASCADE
);

-- Отзывы и рейтинги
CREATE TABLE IF NOT EXISTS reviews (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT        NOT NULL,
    field_id   BIGINT        NOT NULL,
    rating     INT           NOT NULL,
    comment    VARCHAR(1000),
    created_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_review_rating       CHECK (rating >= 1 AND rating <= 5),
    CONSTRAINT uq_review_user_field    UNIQUE (user_id, field_id),
    CONSTRAINT fk_reviews_user  FOREIGN KEY (user_id)  REFERENCES users(id)  ON DELETE CASCADE,
    CONSTRAINT fk_reviews_field FOREIGN KEY (field_id) REFERENCES fields(id) ON DELETE CASCADE
);

-- Токены сброса пароля
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(512) NOT NULL,
    user_id    BIGINT       NOT NULL,
    expires_at TIMESTAMP    NOT NULL,
    used       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_password_reset_token  UNIQUE (token),
    CONSTRAINT fk_password_reset_user   FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Индексы
CREATE INDEX IF NOT EXISTS idx_favorites_user_id    ON favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_favorites_field_id   ON favorites(field_id);
CREATE INDEX IF NOT EXISTS idx_reviews_field_id     ON reviews(field_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id      ON reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_prt_user_id          ON password_reset_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_prt_token            ON password_reset_tokens(token);
