-- V3: owner verification, push tokens, chat rooms, field reports

-- Add verification fields to users (standard ALTER TABLE, no IF NOT EXISTS for H2 compat)
ALTER TABLE users ADD COLUMN verification_status VARCHAR(20) NOT NULL DEFAULT 'UNVERIFIED';
ALTER TABLE users ADD COLUMN phone_verified      BOOLEAN     NOT NULL DEFAULT FALSE;

CREATE INDEX idx_users_verification ON users(verification_status);

-- Push notification device tokens
CREATE TABLE device_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    token      VARCHAR(500) NOT NULL UNIQUE,
    platform   VARCHAR(10)  NOT NULL DEFAULT 'IOS',
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_device_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_device_tokens_user ON device_tokens(user_id);

-- Chat rooms (one per booking)
CREATE TABLE chat_rooms (
    id         BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT    NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_room_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE
);

-- Chat messages
CREATE TABLE chat_messages (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id          BIGINT      NOT NULL,
    sender_username  VARCHAR(50) NOT NULL,
    content          TEXT        NOT NULL,
    sent_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_read          BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_chat_message_room FOREIGN KEY (room_id) REFERENCES chat_rooms(id) ON DELETE CASCADE
);

CREATE INDEX idx_chat_messages_room_time ON chat_messages(room_id, sent_at);

-- Field reports / complaints
CREATE TABLE field_reports (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id   BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    reason     VARCHAR(500) NOT NULL,
    resolved   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_report_field FOREIGN KEY (field_id) REFERENCES fields(id)  ON DELETE CASCADE,
    CONSTRAINT fk_report_user  FOREIGN KEY (user_id)  REFERENCES users(id)   ON DELETE CASCADE
);
