-- ═══════════════════════════════════════════════════════════════════
-- V3 — Owner verification, device tokens (push), chat, booking flow
-- ═══════════════════════════════════════════════════════════════════

-- ── Верификация владельцев ────────────────────────────────────────
ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_status VARCHAR(20) NOT NULL DEFAULT 'UNVERIFIED';
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_verified      BOOLEAN      NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_users_verification ON users(verification_status);

-- ── Push-уведомления: токены устройств ────────────────────────────
CREATE TABLE IF NOT EXISTS device_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    token      VARCHAR(500) NOT NULL,
    platform   VARCHAR(10)  NOT NULL DEFAULT 'IOS',
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_device_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_device_token       UNIQUE (token)
);

CREATE INDEX IF NOT EXISTS idx_device_tokens_user ON device_tokens(user_id);

-- ── Подтверждение/отклонение бронирований (PENDING → CONFIRMED/REJECTED) ──
-- BookingStatus уже содержит PENDING, статус теперь PENDING при создании
-- (реализовано в BookingService — поле status по умолчанию PENDING)

-- ── Чат: комнаты ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS chat_rooms (
    id         BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT    NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_room_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
    CONSTRAINT uq_chat_room_booking UNIQUE (booking_id)
);

-- ── Чат: сообщения ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS chat_messages (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id          BIGINT       NOT NULL,
    sender_username  VARCHAR(50)  NOT NULL,
    content          TEXT         NOT NULL,
    sent_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_read          BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_chat_message_room FOREIGN KEY (room_id) REFERENCES chat_rooms(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_room_time ON chat_messages(room_id, sent_at);

-- ── Жалобы на площадки ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS field_reports (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id   BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    reason     VARCHAR(500) NOT NULL,
    resolved   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_report_field FOREIGN KEY (field_id) REFERENCES fields(id) ON DELETE CASCADE,
    CONSTRAINT fk_report_user  FOREIGN KEY (user_id)  REFERENCES users(id)  ON DELETE CASCADE
);
